import { createSelector } from '@ngrx/store';
import { tasksFeature } from './task.reducers';
import { taskAdapter } from './task.state';

// Auto-generated by createFeature — selects the whole tasks slice
export const {
  selectTasksState, // the full slice
  selectLoading, // state.loading
  selectError, // state.error
} = tasksFeature;

// Entity adapter selectors — derive the actual task arrays from ids + entities
const { selectAll, selectEntities, selectTotal } = taskAdapter.getSelectors();

export const selectAllTasks = createSelector(selectTasksState, selectAll);
export const selectTaskEntities = createSelector(selectTasksState, selectEntities);
export const selectTaskCount = createSelector(selectTasksState, selectTotal);

// Derived selectors
export const selectCompletedTasks = createSelector(selectAllTasks, (tasks) =>
  tasks.filter((t) => t.completed),
);
export const selectPendingTasks = createSelector(selectAllTasks, (tasks) =>
  tasks.filter((t) => !t.completed),
);
